### ISSUE TITLE
Way to contact you

### ISSUE THREAD

**Issue by sdelamo** [altro3/micronaut3-bug#1]
Hi @altro3 could I contact you via email?

Would you be interested in applying to work on Micronaut 

We are looking for a developer to join the Micronaut Open-Source team. If you are interested in building the best JVM framework, email me at: delamos@objectcomputing.com full-remote. 

https://jobs.lever.co/oci/6d0bd22e-e943-4b80-81fd-c613724e4a33

**Comment by altro3** [comment]
@sdelamo hi! Thank you for your offer! Very pleasant :-). I will write to you tomorrow

**Comment by altro3** [comment]
@sdelamo and yes, you can send me messege by email

**Comment by sdelamo** [comment]
You don't have any profile information associated to your GitHub username. You are hard to reach ;-)
